### ISSUE TITLE
screen flash on vim startup

### ISSUE THREAD

**Issue by beautiful-boyyy** [xiyaowong/nvim-transparent#15]
![output](https://user-images.githubusercontent.com/66351806/209352463-2ea47f74-b192-4e30-9e16-18564a69c7e8.gif)

**Comment by xiyaowong** [comment]
?

**Comment by beautiful-boyyy** [comment]
> ?
就是会先加载我配置的主题然后再透明

**Comment by beautiful-boyyy** [comment]
> ?

就是会先加载我配置的主题然后再透明

**Comment by xiyaowong** [comment]
> > ?
> 
> 就是会先加载我配置的主题的背景色然后再透明

是预期现象
