### ISSUE TITLE
adjust  transparency

### ISSUE THREAD

**Issue by feedoom** [xiyaowong/nvim-transparent#2]
It would be nice if can adjust the transparency

![image](https://user-images.githubusercontent.com/37018475/128382154-08ddbb14-ff25-4b71-9057-60340db5e22d.png)

**Comment by xiyaowong** [comment]
It seems impossible

**Comment by tusharsingh09** [comment]
It adjusts to the opacity of your terminal emulator, for example i use Alacritty at 0.9 opacity. Calling `:TransparentEnable` sets my neovim transparency to 0.9 as well.
