### ISSUE TITLE
Install help

### ISSUE THREAD

**Issue by JiroRauwers** [xiyaowong/nvim-transparent#22]
Hey I'm new to nvim, I just installed astrovim to try it out, I got myself lost on how can i add this plugin to my config. Can I get some directions on how to do or where to look out

**Comment by xiyaowong** [comment]
#### Example with Packer

[wbthomason/packer.nvim](https://github.com/wbthomason/packer.nvim)

```lua
-- init.lua
require("packer").startup(
    function()
        use {
            'xiyaowong/nvim-transparent'
        }
    end
)
```

#### Example with Plug

[junegunn/vim-plug](https://github.com/junegunn/vim-plug)

```vim
" init.vim
call plug#begin('~/.vim/plugged')
Plug 'xiyaowong/nvim-transparent'
call plug#end()
```

#### Example with Lazy

[folke/lazy.nvim](https://github.com/folke/lazy.nvim)

```lua
-- init.lua
require('lazy').setup({
    {
        'xiyaowong/nvim-transparent'
    }
})
```
