### ISSUE TITLE
How can I make plugin fidget transparent?

### ISSUE THREAD

**Issue by zsmatrix62** [xiyaowong/nvim-transparent#23]
This is the plugin for showing progress of nvim lsp [https://github.com/j-hui/fidget.nvim](https://github.com/j-hui/fidget.nvim)

<img width="499" alt="image" src="https://user-images.githubusercontent.com/2951879/220863262-94ca5f06-f916-4678-944a-162e72986458.png">

**Comment by xiyaowong** [comment]
float window can't be transparent. `:h winblend`

**Comment by ingur** [comment]
@zsmatrix62 In case you were still wondering, u can make fidget transparent by turning off the winblend of fidget, something like:
```lua
    {
        "j-hui/fidget.nvim",
        opts = {
            window = {
                blend = 0,
            }
        },
    },
```
