### ISSUE TITLE
How to set Transparency at Start init.lua

### ISSUE THREAD

**Issue by dedguy21** [xiyaowong/nvim-transparent#3]
New to Neovim , need help with the lua script ...
I get this error when trying to put this command in the settings

E492: Not an editor command: TransparentEnable

This plugin works better than I hoped. Just for some reason, I'm not able to get transparency from the start. I also get an error when trying to set  TransparentEnable as a neovim command or global option.

I'm trying to write the Lua, but if it has to be vimscript I'll do that too. 
I would like my terminal to be transparent when opening nvim, and I choose if I want to disable it.

**Comment by xiyaowong** [comment]
recomment to use global variable `let g:transparent_enabled = v:true`, for lua `vim.g.transparent_enabled = true`
