### ISSUE TITLE
Transparency doesn't apply for tokyonight.nvim theme

### ISSUE THREAD

**Issue by Dyzean** [xiyaowong/nvim-transparent#4]
Transparency doesn't apply with [tokyonight.nvim](https://github.com/folke/tokyonight.nvim) theme when NvimTree opened.

https://user-images.githubusercontent.com/69681505/142169728-c644db3f-61d4-4443-ad64-e6f24a7cc442.mp4

as you can see here.

**Comment by Dyzean** [comment]
nvim-transparent config
```lua
local transparent = require 'transparent'

transparent.setup({
  enable = true,
  extra_groups = {
    "StatusLineNC",
    "StatusLine",
    "NvimTreeStatusLine"
  },
  exclude = {
    "BufferLineTabClose",
    "BufferlineBufferSelected",
    "BufferLineFill",
    "BufferLineBackground",
    "BufferLineSeparator",
    "BufferLineIndicatorSelected"
  },
})
```

**Comment by Dyzean** [comment]
pft. i found the issue, i didn't read the theme docs, sorry for this 😅

**Comment by yigitkalan** [comment]
I now this issue is a bit old but hat was the thing that you missed on the theme doc i am having the same issue
