### ISSUE TITLE
no change on command TransparentDisable and TransparentToggle

### ISSUE THREAD

**Issue by Allaman** [xiyaowong/nvim-transparent#6]
Hello,

when starting neovim with transparent enabled = false and then trigger `:TransparentEnable` it works as expected - Neovim gets transparent. When calling `:TransparentDisable` or `:TransparentToggle` the transparency does not change back to opaque. No messages or errors. 
I am running Alacritty as terminal emulator with `background_opacity: 0.7`

**Comment by xiyaowong** [comment]
What theme are you using?

**Comment by UniqueDing** [comment]
so I am, and my colorscheme is dracula, thanks

**Comment by xiyaowong** [comment]
try to add this line ![image](https://user-images.githubusercontent.com/47070852/144229669-d89e6510-880b-4950-b90f-ba882c75bc75.png) @Allaman @UniqueDing

**Comment by UniqueDing** [comment]
I try, it not run this print

**Comment by xiyaowong** [comment]
@UniqueDing `require` only run one time https://github.com/glepnir/zephyr-nvim/blob/32c4ea97cc1cd3db1abebd46aff2ee18d66d8d59/colors/zephyr.vim#L6
