### ISSUE TITLE
Only the window with focus is transparent

### ISSUE THREAD

**Issue by zakissimo** [xiyaowong/nvim-transparent#8]
![Peek 2022-04-06 23-45](https://user-images.githubusercontent.com/64891486/162077226-e0a98582-c4fd-4313-b0c2-e51e336fd1a9.gif)

I'm sorry if I misunderstood the proper config, but as you can see, only the window with cursor get transparency applied.

**Comment by zakissimo** [comment]
Okay, so I removed pywal config in .zshrc, and now it's always transparent and the toggle doesn't change a thing. I'm confused.

**Comment by xiyaowong** [comment]
Should be fixed now
